import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  assertCanonicalTiming,
  assertSubmissionRuntimeProvenance,
  assertYouTubeRuntimeProvenance,
  classifyChecklistItem,
  classifyYouTubeReference,
  inspectPng,
  mp4DurationSeconds,
  normalizedWords,
  parseHashManifest,
  readRegularFile,
  runSubmissionReadiness,
  sha256,
  submissionExitCode,
  validateCandidateNames,
  validatePng,
  validateWebVtt,
  verifyPinnedHash,
} from "../scripts/submission-readiness";

const root = process.cwd();
const assets = path.join(root, "submission-assets");
const unsafeFontReference = /(?:(?:file:|[A-Za-z]:[\\/]|\\\\(?:\?\\UNC\\|[^\\/\s"'`<>]+[\\/]))[^"'`<>\r\n)]{0,32767})\.(?:woff2?|ttf|otf)\b/iu;

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function cssRule(css: string, selector: string, property?: string): string {
  const matches = [...css.matchAll(new RegExp(`(?:^|(?<=[{}]))\\s*${escapeRegExp(selector)}\\s*\\{([^{}]*)\\}`, "g"))]
    .map((match) => match[1])
    .filter((rule) => !property || new RegExp(`(?:^|;)\\s*${escapeRegExp(property)}\\s*:`, "i").test(rule));
  assert.equal(matches.length, 1, `${selector} must resolve to exactly one flat CSS rule${property ? ` declaring ${property}` : ""}`);
  return matches[0];
}

function cssDeclaration(rule: string, property: string): string {
  const matches = [...rule.matchAll(new RegExp(`(?:^|;)\\s*${escapeRegExp(property)}\\s*:\\s*([^;]+)`, "gi"))];
  assert.equal(matches.length, 1, `${property} must resolve to exactly one declaration`);
  return matches[0][1].trim();
}

function resolveCssColor(css: string, value: string): string {
  const variable = value.match(/^var\((--[a-z0-9-]+)\)$/i)?.[1];
  return variable ? cssDeclaration(cssRule(css, ":root", variable), variable) : value;
}

function relativeLuminance(hex: string): number {
  assert.match(hex, /^#[0-9a-f]{6}$/i, `expected an exact six-digit CSS color, received ${hex}`);
  const channels = [1, 3, 5].map((offset) => Number.parseInt(hex.slice(offset, offset + 2), 16) / 255);
  const linear = channels.map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
}

function contrastRatio(foreground: string, background: string): number {
  const foregroundLuminance = relativeLuminance(foreground);
  const backgroundLuminance = relativeLuminance(background);
  return (Math.max(foregroundLuminance, backgroundLuminance) + 0.05)
    / (Math.min(foregroundLuminance, backgroundLuminance) + 0.05);
}

test("the sealed submission package passes locally and exposes only authority-gated work", async () => {
  const checks = await runSubmissionReadiness(root);
  assert.deepEqual(checks.filter((check) => check.state === "FAIL"), []);
  assert.deepEqual(
    checks.filter((check) => check.state === "PENDING").map((check) => check.name),
    ["Public YouTube URL", "Devpost media transmission", "Rules acceptance and final submit"],
  );
  assert.equal(submissionExitCode(checks), 0);
  assert.equal(submissionExitCode(checks, true), 1);
  const submission = await readFile(path.join(root, "SUBMISSION.md"), "utf8");
  assert.doesNotThrow(() => assertSubmissionRuntimeProvenance(submission));
  assert.throws(
    () => assertSubmissionRuntimeProvenance(submission.replace("Production version 8 at audited runtime commit", "Production version 7 at audited runtime commit")),
    /submission runtime provenance/,
  );
  assert.throws(
    () => assertSubmissionRuntimeProvenance(submission.replace("proof-producing version 7 runtime", "proof-producing version 8 runtime")),
    /submission runtime provenance/,
  );
  assert.throws(
    () => assertSubmissionRuntimeProvenance(`${submission}\nProduction version 7 at audited runtime commit \`042215042dd46ded14b501f961f4d9e7debb8178\` passes 48 tests.`),
    /competing production-runtime claim/,
  );
  const youtubeMetadata = await readFile(path.join(root, "YOUTUBE_METADATA.md"), "utf8");
  assert.doesNotThrow(() => assertYouTubeRuntimeProvenance(youtubeMetadata));
  assert.throws(
    () => assertYouTubeRuntimeProvenance(youtubeMetadata.replace("generated by version 7 runtime", "generated by version 8 runtime")),
    /YouTube runtime provenance/,
  );
  assert.throws(
    () => assertYouTubeRuntimeProvenance(youtubeMetadata.replace("f7f8f529285ed9e01fdbe02e868833fc86de5475", "042215042dd46ded14b501f961f4d9e7debb8178")),
    /YouTube runtime provenance/,
  );
  assert.throws(
    () => assertYouTubeRuntimeProvenance(`${youtubeMetadata}\nThe proof was generated by version 8 runtime \`f7f8f529285ed9e01fdbe02e868833fc86de5475\`.`),
    /competing proof-runtime claim/,
  );

  const layout = await readFile(path.join(root, "app", "layout.tsx"), "utf8");
  const css = await readFile(path.join(root, "app", "globals.css"), "utf8");
  assert.match("file:///C:/build/font.woff2", unsafeFontReference);
  assert.match("C:/build/font.woff2", unsafeFontReference);
  assert.match("C:\\build\\font.woff2", unsafeFontReference);
  assert.match(String.raw`\\server\share\font.woff2`, unsafeFontReference);
  assert.match(String.raw`\\?\UNC\server\share\font.woff2`, unsafeFontReference);
  assert.match(`C:/${"nested/".repeat(200)}font.woff2`, unsafeFontReference);
  assert.doesNotMatch("/fonts/font.woff2", unsafeFontReference);
  assert.throws(
    () => cssRule(".mobile.original-address { color: #ffffff; }", ".original-address", "color"),
    /exactly one flat CSS rule/u,
  );
  assert.throws(
    () => cssRule(".original-address{color:#ffffff}.original-address{color:#000000}", ".original-address", "color"),
    /exactly one flat CSS rule/u,
  );
  assert.doesNotMatch(layout, /from\s+["']next\/font(?:\/google|\/local)?["']/u);
  assert.doesNotMatch(`${layout}\n${css}`, unsafeFontReference);
  assert.match(layout, /import\s+\{\s*preload\s*\}\s+from\s+["']react-dom["']/u);
  assert.match(layout, /preload\(\s*["']\/fonts\/geist-latin\.woff2["'][\s\S]{0,180}as:\s*["']font["'][\s\S]{0,180}type:\s*["']font\/woff2["'][\s\S]{0,180}crossOrigin:\s*["']anonymous["']/u);
  assert.match(layout, /preload\(\s*["']\/fonts\/cormorant-garamond-latin\.woff2["'][\s\S]{0,180}as:\s*["']font["'][\s\S]{0,180}type:\s*["']font\/woff2["'][\s\S]{0,180}crossOrigin:\s*["']anonymous["']/u);
  assert.match(css, /url\(["']\/fonts\/geist-latin\.woff2["']\)/u);
  assert.equal(css.match(/url\(["']\/fonts\/cormorant-garamond-latin\.woff2["']\)/gu)?.length, 4);

  const fontContracts = [
    ["geist-latin.woff2", 29_288, "9B6F5FF45B278C744B5F379A2C4ECBAF858A842B8EAF82AC8D21B699CA16C608"],
    ["cormorant-garamond-latin.woff2", 37_776, "5D618C462B7A5B74F442E1548880086AF71764D9CC7D35C16AB45353DA934621"],
  ] as const;
  for (const [name, size, hash] of fontContracts) {
    const font = await readFile(path.join(root, "public", "fonts", name));
    assert.equal(font.subarray(0, 4).toString("ascii"), "wOF2", `${name} must be WOFF2`);
    assert.equal(font.length, size, `${name} byte length drifted`);
    assert.equal(sha256(font), hash, `${name} hash drifted`);
  }
  const geistLicense = await readFile(path.join(root, "public", "fonts", "LICENSE-Geist.txt"), "utf8");
  const cormorantLicense = await readFile(path.join(root, "public", "fonts", "LICENSE-Cormorant-Garamond.txt"), "utf8");
  assert.match(geistLicense, /Copyright 2024 The Geist Project Authors/u);
  assert.match(cormorantLicense, /Copyright 2015 the Cormorant Project Authors/u);
  assert.match(geistLicense, /SIL OPEN FONT LICENSE Version 1\.1/u);
  assert.match(cormorantLicense, /SIL OPEN FONT LICENSE Version 1\.1/u);

  const surfaceBackgrounds = {
    returned: cssDeclaration(cssRule(css, ".returned-shell", "background"), "background"),
    paper: cssDeclaration(cssRule(css, ".paper-surface", "background"), "background"),
  } as const;
  const contrastContracts = [
    [".original-address", "returned"],
    [".restored-nav a.missing-link", "returned"],
    [".source-count", "paper"],
    [".recovered-image figcaption", "paper"],
    [".overview-evidence-summary span", "paper"],
    [".returned-footer", "returned"],
  ] as const;
  assert.equal(contrastContracts.length, 6);
  assert.equal(contrastRatio("#000000", "#ffffff"), 21);
  assert.ok(contrastRatio("#707a81", "#101419") < 4.5, "the original low-contrast token must remain a rejecting fixture");
  for (const [selector, surface] of contrastContracts) {
    const foreground = resolveCssColor(css, cssDeclaration(cssRule(css, selector, "color"), "color"));
    const background = resolveCssColor(css, surfaceBackgrounds[surface]);
    const ratio = contrastRatio(foreground, background);
    assert.ok(ratio >= 4.5, `${selector} contrast ${ratio.toFixed(3)}:1 is below WCAG AA 4.5:1`);
  }
});

test("checksum manifests reject line-ending drift and role reordering", () => {
  const a = "A".repeat(64);
  const b = "B".repeat(64);
  const names = ["first.png", "second.png"];
  const valid = Buffer.from(`${a}  first.png\n${b}  second.png\n`, "ascii");
  assert.deepEqual([...parseHashManifest(valid, names).keys()], names);
  assert.throws(() => parseHashManifest(Buffer.from(valid.toString("ascii").replace(/\n/g, "\r\n"), "ascii"), names), /LF line endings/);
  assert.throws(() => parseHashManifest(Buffer.from(`${b}  second.png\n${a}  first.png\n`, "ascii"), names), /expected first\.png/);
  assert.throws(() => parseHashManifest(Buffer.from(`${a}  wrong.mp4\n`, "ascii"), ["master.mp4"]), /expected master\.mp4/);
  assert.throws(() => parseHashManifest(Buffer.from(`${a}  master.mp4\n${b}  extra.mp4\n`, "ascii"), ["master.mp4"]), /2 entries/);
});

test("a mutable sidecar cannot rebaseline content away from a pinned role hash", () => {
  const stale = Buffer.from("stale media");
  const mutableSidecar = Buffer.from(`${sha256(stale)}  master.mp4\n`, "ascii");
  assert.equal(parseHashManifest(mutableSidecar, ["master.mp4"]).get("master.mp4"), sha256(stale));
  assert.throws(() => verifyPinnedHash(stale, "A".repeat(64), "sealed master"), /expected A{64}/);
});

test("WebVTT validation is integer-timed, ordered, and fail-closed", () => {
  const valid = [
    "WEBVTT",
    "",
    "00:00:00.100 --> 00:00:00.900",
    "First cue.",
    "",
    "00:00:00.900 --> 00:00:01.500",
    "Second cue.",
    "",
  ].join("\n");
  const cues = validateWebVtt(valid, 2, 1500);
  assert.deepEqual(cues.map((cue) => [cue.startMs, cue.endMs]), [[100, 900], [900, 1500]]);
  assert.throws(() => validateWebVtt(valid.replace("00:00:00.900 --> 00:00:01.500", "00:00:00.899 --> 00:00:01.500"), 2, 1500), /overlap/);
  assert.throws(() => validateWebVtt(valid.replace("00:00:01.500", "00:00:01.501"), 2, 1500), /after the video/);
  assert.throws(() => validateWebVtt(valid, 3, 1500), /expected 3/);
  assert.throws(() => validateWebVtt(valid.replace("WEBVTT", "WEB-VTT"), 2, 1500), /begin with WEBVTT/);
  assert.throws(() => validateWebVtt(valid.replace("00:00:00.100 --> 00:00:00.900", "00:00:00.900 --> 00:00:00.100"), 2, 1500), /end after/);
  assert.throws(() => validateWebVtt(valid.replace("First cue.", ""), 2, 1500), /no text|timing line/);
});

test("PNG validation rejects a role-preserving geometry mutation", async () => {
  const thumbnail = await readFile(path.join(assets, "07-youtube-thumbnail.png"));
  const info = validatePng(thumbnail, 1280, 720);
  assert.equal(info.colorType, 2);
  const mutated = Buffer.from(thumbnail);
  mutated.writeUInt32BE(1279, 16);
  assert.equal(inspectPng(mutated).width, 1279);
  assert.throws(() => validatePng(mutated, 1280, 720), /expected 1280x720/);
  const wrongSignature = Buffer.from(thumbnail);
  wrongSignature[0] = 0;
  assert.throws(() => inspectPng(wrongSignature), /signature/);
  assert.throws(() => inspectPng(thumbnail.subarray(0, thumbnail.length - 1)), /IEND/);
  const withAlpha = Buffer.from(thumbnail);
  withAlpha[25] = 6;
  assert.throws(() => validatePng(withAlpha, 1280, 720), /color type 6/);
});

test("the MP4 parser reads the sealed master duration without external binaries", async () => {
  const master = await readFile(path.join(assets, "alexandria-here-build-week-demo.mp4"));
  assert.ok(Math.abs(mp4DurationSeconds(master) - 155.258) < 0.001);
  assert.throws(() => mp4DurationSeconds(master.subarray(8)), /ftyp|MP4 box/);
});

test("narration comparison tolerates punctuation but not changed words", () => {
  assert.deepEqual(normalizedWords("hostile-HTML — evidence"), normalizedWords("hostile HTML evidence"));
  assert.notDeepEqual(normalizedWords("evidence is present"), normalizedWords("evidence was present"));
});

test("YouTube reference state permits exactly one pending marker or one published URL", () => {
  assert.equal(classifyYouTubeReference("Demo: [ADD PUBLIC YOUTUBE URL — UNDER 3 MINUTES]"), "pending");
  assert.equal(classifyYouTubeReference("Demo: https://youtu.be/abc_123"), "present");
  assert.throws(() => classifyYouTubeReference("Demo: [TODO VIDEO]"), /unsupported placeholders/);
  assert.throws(() => classifyYouTubeReference("Demo: [ADD PUBLIC YOUTUBE URL — UNDER 3 MINUTES] https://youtu.be/abc_123"), /both/);
});

test("authority checklist items are exact, unique, and tri-state", () => {
  const label = "Perform the authority-gated action.";
  assert.equal(classifyChecklistItem(`- [ ] ${label}`, label), "pending");
  assert.equal(classifyChecklistItem(`- [x] ${label}`, label), "complete");
  assert.throws(() => classifyChecklistItem("", label), /exactly once/);
  assert.throws(() => classifyChecklistItem(`- [ ] ${label}\n- [ ] ${label}`, label), /exactly once/);
  assert.throws(() => classifyChecklistItem(`- [ ] ${label}\n- [x] ${label}`, label), /exactly once/);
  assert.throws(() => classifyChecklistItem(`- [ ] Perform a reworded action.`, label), /exactly once/);
});

test("canonical timing rejects alternate runtime and deadline claims", () => {
  const valid = "Runtime: less than 3:00. Submit July 21, 2026 at 5:00 PM PDT (Pacific Time).";
  assert.doesNotThrow(() => assertCanonicalTiming(valid, "fixture"));
  for (const contradiction of ["at most 3:00", "3:00 or under", "3 minutes or under", "three minutes or less", "no more than 3 minutes", "≤ 3:00"]) {
    assert.throws(() => assertCanonicalTiming(`${valid} Also ${contradiction}.`, "fixture"), /runtime/);
  }
  assert.throws(() => assertCanonicalTiming(`${valid} Alternate July 21, 2026 at 4:00 PM PDT (Pacific Time).`, "fixture"), /deadline/);
});

test("candidate roles reject stale alternates and final mode passes only explicit completion", () => {
  validateCandidateNames(["08-devpost-cover.png", "09-devpost-gallery.png"], ["08-devpost-cover.png", "09-devpost-gallery.png"], "fixture");
  assert.throws(() => validateCandidateNames(["08-devpost-cover-old.png", "08-devpost-cover.png"], ["08-devpost-cover.png"], "fixture"), /candidates/);
  assert.equal(submissionExitCode([{ section: "External authority", name: "done", state: "PASS", detail: "explicit" }], true), 0);
});

test("regular-file limits are checked before reads, including decimal 5 MB", async () => {
  const temporary = await mkdtemp(path.join(os.tmpdir(), "alexandria-submission-test-"));
  try {
    const exact = path.join(temporary, "exact.bin");
    const tooLarge = path.join(temporary, "too-large.bin");
    const directory = path.join(temporary, "directory");
    await Promise.all([
      writeFile(exact, Buffer.alloc(5_000_000)),
      writeFile(tooLarge, Buffer.alloc(5_000_001)),
      mkdir(directory),
    ]);
    assert.equal((await readRegularFile(exact, { maxBytes: 5_000_000 })).length, 5_000_000);
    await assert.rejects(readRegularFile(tooLarge, { maxBytes: 5_000_000 }), /exceeds 5000000/);
    await assert.rejects(readRegularFile(directory), /regular, non-symlink/);
    const link = path.join(temporary, "link.bin");
    try {
      await symlink(exact, link, "file");
      await assert.rejects(readRegularFile(link), /regular, non-symlink/);
    } catch (error) {
      const code = error && typeof error === "object" && "code" in error ? String(error.code) : "";
      if (!new Set(["EPERM", "EACCES", "ENOSYS"]).has(code)) throw error;
    }
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
});
